### ISSUE TITLE
why requests_html when we can use requests module...

### ISSUE THREAD

**Issue by devsanthoshmk** [christivn/mapScraper#2]
using requests will save the running time a lot...
I'm just curious to know why and how did you find that url i have been searching that for week thank you so much!!!!!!!

**Comment by christivn** [comment]
The script use "requests_html" instead of "requests" because it is necessary to render the Javascript content to scrape the data, google maps initially loads a blank page without data and loads it later with Javascript.

The "requests" package does not offer the option to render JS, "requests-html" uses "pyppeteer" to do the rendering, which is a headless browser. 


The URL:
**_https:/ /www.google.com/localservices/prolist?hl=en&ssta=1&q= `query` &oq= `query` &src=2&lci= `pagination`_**

Searching on google my business profiles i found the url: https://www.google.com/localservices/prolist
I cleaned up a bit the url that it generates when doing a search there and I kept the necessary parameters to get the final url.

I hope the script and url will be helpful for your projects 😄
